import { Pregunta } from '../models/game.models';

export const LOCAL_PREGUNTAS: Pregunta[] = [
  {
    enunciado: '¿Qué comando de Angular CLI se utiliza para crear un nuevo componente?',
    opciones: ['ng make component', 'ng generate component', 'ng build component', 'ng create component'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Para qué sirve la directiva *ngFor en Angular?',
    opciones: ['Para iterar y repetir elementos en la plantilla', 'Para ocultar o mostrar un elemento', 'Para navegar a otra ruta', 'Para conectar un formulario'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál directiva estructural se utiliza para mostrar u ocultar un elemento según una condición?',
    opciones: ['*ngSwitch', '*ngIf', '*ngShow', '*ngDisplay'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué es un Service en Angular?',
    opciones: ['Un archivo de estilos CSS', 'Una clase para compartir lógica y datos entre componentes', 'Una vista de usuario', 'Una etiqueta HTML'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué decorador permite recibir datos desde un componente padre?',
    opciones: ['@Output()', '@Injectable()', '@Input()', '@ViewChild()'],
    correcta: 2,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué decorador se utiliza para emitir eventos hacia un componente padre?',
    opciones: ['@Output()', '@Input()', '@HostBinding()', '@Emitter()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál es la sintaxis utilizada para el enlace bidireccional (two-way binding)?',
    opciones: ['{{ngModel}}', '[(ngModel)]', '[ngModel]', '(ngModel)'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué comando se utiliza para compilar y levantar el servidor local de desarrollo?',
    opciones: ['ng start', 'ng run', 'ng serve', 'ng deploy'],
    correcta: 2,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué decorador define una clase como un componente en Angular?',
    opciones: ['@Module()', '@Injectable()', '@Directive()', '@Component()'],
    correcta: 3,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué método del ciclo de vida se ejecuta una sola vez después de inicializar el componente?',
    opciones: ['ngOnChanges', 'ngOnInit', 'ngDoCheck', 'ngOnDestroy'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Para qué sirve el servicio HttpClient en Angular?',
    opciones: ['Para peticiones HTTP/REST a servidores', 'Para animar gráficos 3D', 'Para compilar CSS', 'Para registrar sonidos'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál es el pipe de Angular para convertir texto a mayúsculas?',
    opciones: ['caps', 'toUpper', 'uppercase', 'upper'],
    correcta: 2,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué palabra clave de TypeScript permite definir tipos que no pueden ser reasignados?',
    opciones: ['var', 'let', 'const', 'static'],
    correcta: 2,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál de los siguientes es un tipo primitivo en TypeScript y JavaScript?',
    opciones: ['boolean', 'Component', 'Observable', 'HTMLElement'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué clase de RxJS permite emitir valores reactivos a múltiples suscriptores?',
    opciones: ['Subject', 'Promise', 'Array', 'Record'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué método de Three.js renderiza la escena con la cámara especificada?',
    opciones: ['renderer.render(scene, camera)', 'renderer.draw()', 'scene.paint(camera)', 'camera.capture(scene)'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué geometría de Three.js se usa para crear un cubo o caja 3D?',
    opciones: ['BoxGeometry', 'SphereGeometry', 'PlaneGeometry', 'CylinderGeometry'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué directiva de atributo se usa para cambiar estilos CSS dinámicamente?',
    opciones: ['[ngStyle]', '[styleAdd]', '[cssBind]', '[styleSheet]'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál es el operador ternario en JavaScript y TypeScript?',
    opciones: ['condicion ? trueVal : falseVal', 'condicion ?? falseVal', 'if (condicion) -> trueVal', 'condicion && trueVal'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué método de array en JavaScript transforma cada elemento devolviendo un nuevo array?',
    opciones: ['filter()', 'map()', 'reduce()', 'forEach()'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál es el propósito del archivo angular.json?',
    opciones: ['Configurar el espacio de trabajo y compilación del proyecto Angular', 'Guardar contraseñas de la base de datos', 'Definir rutas del backend', 'Crear animaciones CSS'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué propiedad de @Component permite usar componentes independientes sin NgModule en Angular 17+?',
    opciones: ['standalone: true', 'independent: true', 'modular: false', 'isolated: true'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué hook del ciclo de vida se ejecuta cuando se destruye un componente para limpiar recursos?',
    opciones: ['ngAfterViewInit', 'ngOnDestroy', 'ngExit', 'ngCleanup'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál es el operador de TypeScript para acceder con seguridad a propiedades que pueden ser null o undefined?',
    opciones: ['?. (optional chaining)', '!: (assertion)', '?? (nullish coalescing)', '&& (and)'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué tipo de material en Three.js reacciona a las luces y sombras de la escena?',
    opciones: ['MeshStandardMaterial', 'MeshBasicMaterial', 'LineBasicMaterial', 'SpriteMaterial'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué puerto por defecto utiliza la aplicación cliente de Angular con ng serve?',
    opciones: ['3000', '4200', '8080', '5000'],
    correcta: 1,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué método de Socket.IO en el cliente escucha un evento emitido por el servidor?',
    opciones: ['socket.on("evento", callback)', 'socket.listen("evento")', 'socket.emit("evento")', 'socket.subscribe("evento")'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué método de Socket.IO en el cliente envía un mensaje hacia el servidor?',
    opciones: ['socket.emit("evento", datos)', 'socket.sendMsg("evento")', 'socket.post("evento")', 'socket.dispatch("evento")'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál es la función matemática en JavaScript para generar números decimales pseudoaleatorios entre 0 y 1?',
    opciones: ['Math.random()', 'Math.floor()', 'Math.round()', 'Math.ceil()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué función en JavaScript convierte un string en formato JSON a un objeto?',
    opciones: ['JSON.parse()', 'JSON.stringify()', 'JSON.toObject()', 'JSON.decode()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué función en JavaScript convierte un objeto en un string de texto JSON?',
    opciones: ['JSON.stringify()', 'JSON.parse()', 'JSON.encode()', 'JSON.toString()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué decorador en NestJS define una clase como controlador HTTP?',
    opciones: ['@Controller()', '@Injectable()', '@Module()', '@Resolver()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué decorador en NestJS marca una clase como pasarela de WebSocket?',
    opciones: ['@WebSocketGateway()', '@SocketServer()', '@GatewayIO()', '@WsHandler()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué método de array en JavaScript busca si al menos un elemento cumple una condición?',
    opciones: ['some()', 'every()', 'find()', 'includes()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Cuál es la estructura de datos que almacena elementos únicos sin duplicados en JavaScript?',
    opciones: ['Set', 'Map', 'WeakMap', 'Array'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué API web nativa permite reproducir y sintetizar efectos de audio dinámicos en el navegador?',
    opciones: ['Web Audio API', 'Canvas API', 'WebGL API', 'Speech API'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué propiedad CSS permite crear efectos de desenfoque tipo vidrio esmerilado (glassmorphism)?',
    opciones: ['backdrop-filter: blur(...)', 'filter: invert(...)', 'box-shadow: inset', 'opacity: 0.5'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué objeto global de JavaScript se usa para cancelar o ejecutar animaciones a 60 FPS?',
    opciones: ['requestAnimationFrame()', 'setTimeout()', 'setInterval()', 'queueMicrotask()'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué estructura de control de Angular 17+ reemplaza la directiva estructural *ngIf en plantillas?',
    opciones: ['@if (condicion) { ... }', '#if (condicion)', '<ng-if>', '$if (condicion)'],
    correcta: 0,
    dificultad: 'facil',
  },
  {
    enunciado: '¿Qué estructura de control de Angular 17+ reemplaza la directiva *ngFor en plantillas?',
    opciones: ['@for (item of items; track item.id) { ... }', '#for (item in items)', '<ng-repeat>', '$loop (items)'],
    correcta: 0,
    dificultad: 'facil',
  },
];
